### ISSUE TITLE
KR-COMMENT-1 - key compromise

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#179]
KR:

> > Right, we added a new section ("Key Compromise") to describe the
> > problem and how it should be handled.
> > 
> 
> I think this is at least a step in the right direction. I think
> there are 2 keys:
> - The key for the X.509 certificate
> - The key that is negiotatiated during NTS-KE
> 
> Both of them can be compromised, and I think the new section only
> talks about the 2nd key, and talks about how to deal with that
> event, but I think it's also important to deal with the first key.
> 
>

**Comment by ragges** [comment]
Good point. Darn.

**Comment by ragges** [comment]
Problems:
1. The KE server may have been impersonated by an attacker, and that rough KE server would then likely have pointed to a corresponding rouge NTP server, which probably accepts cookies  (including the C2S and S2C keys) from that KE server to be able to do anything useful.
To recover from this:
1a. A new secret key must be generated and a new certificate must be acquired for the KE server.
1b. The certificate for the compromised should be recalled (and we all know how well that works...)
1c. That rough NTP server would have to be taken offline long enough for the cookies to be exhausted and a new KE negotiation with the correct KE server be initiated - OR - all affected clients would have to be told to reinitiate the KE negotiation by some other means.

What more problems would there be?

**Comment by ragges** [comment]
Pushed a patch, but it is more loud thinking than a proposal at this stage.

**Comment by dansarie** [comment]
Ben had a good comment on this:
>I think it's talking about a third key, the one internal to the NTS
server(s) that is used to self-encrypt the cookies that are handed out to
clients.  Compromising this key affects all clients, so is particularly
noteworthy.  Compromising the X.509 key does the same, though is in theory
covered by the security considerations of other documents (e.g., RFC 5280).
Compromising the result of the NTS-KE negotiation affects only the one
client in question, and thus has something of a narrower scope.  I wouldn't
turn down text that discussed the consequences of its compromise, though!

**Comment by dansarie** [comment]
With Ben's comment in mind, I don't think we should change this. The first sentence makes it abundantly clear which key we are talking about:
>If the suggested format for NTS cookies in Section 6 of this draft is
   used, an attacker who has gained access to the secret cookie
   encryption key `K` can impersonate the NTP server, including
   generating new cookies.

**Comment by ragges** [comment]
Yes, but the questions it what happens if the certificate private key gets compromised. I think the questions is valid (or more).

**Comment by dansarie** [comment]
Yes, but as Ben said, that is already well described in other documents, such as RFC 5280, that we have included as normative references. We really shouldn't have to reproduce that advice there.

**Comment by ragges** [comment]
> On 23 Mar 2020, at 09:37, Marcus Dansarie <notifications@github.com> wrote:
> 
> 
> Yes, but as Ben said, that is already well described in other documents, such as RFC 5280, that we have included as normative references. We really shouldn't have to reproduce that advice here.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

There is much more to consider in this case, since clients can have checked out rough cookies and may be using a rough NTP server, in the believe that it is trusted.

**Comment by ragges** [comment]
(A fix should probably include a reference to e.g. RFC 5280 as Ben proposed, my fix currently does not.)

**Comment by dansarie** [comment]
I suggest fixing this by renaming the "Key Compromise" section to "Cookie Encryption Key Compromise", with no other changes to the text.

**Comment by KTeichel** [comment]
I still agree with Marcus and think that making no change other than the proposed change of headline is correct.

1) The document is discussing the most relevant case: the key that is covered by no other document but has a very wide scope if compromised.

2) If an individual cookie is compromised, that should be fine (except in fringe cases) since they are intended for one-time use anyway. Further (and I think we had this discussion on an issue before), if the client discovers the compromise, they know what to do (don't use the  compromised key anymore). If the server discovers it, they cannot really go forward with anything, because they are forbidden from remembering who the associated client is.

3) If a certificate private key is compromised... well, then 
a) as we have noted, there already is a document discussing implications of this case; 
b) the server might not be able to take certain actions because again, they aren't allowed to even remember the list of clients who are affected; 
c) we are (in my own, biased from past experiences, opinion) getting dangerously close to discussing fundamental problems of information security, and must be careful not to tank hours of work into attempts to solve ultimately not well solvable questions such as "what if the server has a certificate, but its operators are malicious?" or "what if someone is secretly using a quantum computer and all our crypto is useless?" or more of "but the client has no time initially, what if they are in 2020 unknowingly using a certificate that expired in 2018?"

**Comment by ragges** [comment]
Still, the other documentation does not cover what that means for NTS, and this is probably the worst thing that could happen to an NTS system - the clients can be talking to a rough NTP server for a long time, thinking that they are talking to the right thing.

That said, I am not opposed to just changing the headline.
