### ISSUE TITLE
RD-1: Section 3

### ISSUE THREAD

**Issue by ragges** [dfoxfranke/nts#81]
RD:
Since NTS is a green field design, is there are reason to be backward compatible to TLS version <1.3?

**Comment by dansarie** [comment]
My opinion on this is well known: Ditch all past TLS versions and go with 1.3 only. Is there any implementation or major distro that only supports 1.2?

**Comment by ragges** [comment]
We could ask Christer, guess he either knows or can check.

**Comment by dsibold** [comment]
Hal gave an reply on the mailing list. From what I remember, he still believes support for TKS 1.2 would be helpful in order to get NTS out. But since more and more operation systems nowadays support TLS 1.3 he could also live if TLS 1.2 would be removed. It is hard for me to judge on this. It would certainly simplifies the document as well as the implementation. For that reason I tend to join the group would would like to get away with TLS 1.2.

**Comment by KTeichel** [comment]
I seem to remember from those discussions the impression that the longer the document is not finalized, the less important the (already abstract) argument for inclusion of 1.2 would be.

Lately, the fact that mandating >=1.3 would represent a technical change has been the main reason why I did not like the option at this stage.
If the situation is now that we need to make technical changes to the document one way or another (i.e. both in case we keep 1.2 as an option and in case we mandate >= 1.3), then I my (underinformed) preference would switch to >= 1.3
